vich_uploader:
    db_driver: orm

    mappings:
        photo:
            uri_prefix: /images/publications
            upload_destination: '%kernel.project_dir%/public/publications'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        pdf:
            uri_prefix: /docs/
            upload_destination: '%kernel.project_dir%/public/docs'
            namer: Vich\UploaderBundle\Naming\UniqidNamer


            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

